solutions/problem-03/estela-master/estudio_covid/panel/urls.py
from django.urls import include, path

from panel import autocomplete, views


urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'error/',
        views.ErrorTestView.as_view(),
    ),
    path(
        'account/', include([
            path(
                '',
                views.AccountDetailView.as_view(),
                name='account_detail'
            ),
            path(
                'login/',
                views.AccountLoginView.as_view(),
                name='account_login'
            ),
            path(
                'logout/',
                views.AccountLogoutView.as_view(),
                name='account_logout'
            ),
            path(
                'password/',
                include([
                    path(
                        '',
                        views.AccountPasswordChangeView.as_view(),
                        name='account_password_change'
                    ),
                    path(
                        'done/',
                        views.AccountPasswordChangeDoneView.as_view(),
                        name='account_password_change_done'
                    ),

                ])
            ),
            path(
                'password-reset/',
                include([
                    path(
                        '',
                        views.AccountPasswordResetView.as_view(),
                        name='account_password_reset'
                    ),
                    path(
                        'complete/',
                        views.AccountPasswordResetCompleteView.as_view(),
                        name='account_password_reset_complete'
                    ),
                    path(
                        '<uidb64>/<token>/',
                        views.AccountPasswordResetConfirmView.as_view(),
                        name='account_password_reset_confirm'
                    ),
                    path(
                        'done/',
                        views.AccountPasswordResetDoneView.as_view(),
                        name='account_password_reset_done'
                    ),
                ])
            ),
            path(
                'change/',
                views.AccountUpdateView.as_view(),
                name='account_change'
            )
        ])
    ),
    path(
        'questions/', include([
            path(
                '',
                views.QuestionListView.as_view(),
                name='question_list'
            ),
            path(
                'add/',
                views.QuestionCreateView.as_view(),
                name='question_add'
            ),
            path(
                '<pk>/',
                include([
                    path(
                        '',
                        views.QuestionDetailView.as_view(),
                        name='question_detail'
                    ),
                    path(
                        'change/',
                        views.QuestionUpdateView.as_view(),
                        name='question_change'
                    ),
                    path(
                        'delete/',
                        views.QuestionDeleteView.as_view(),
                        name='question_delete'
                    ),
                ])
            )
        ])
    ),
    path(
        'questionnaires/', include([
            path(
                '',
                views.QuestionnaireListView.as_view(),
                name='questionnaire_list'
            ),
            path(
                'add/',
                views.QuestionnaireCreateView.as_view(),
                name='questionnaire_add'
            ),
            path(
                'autocomplete/',
                autocomplete.QuestionnaireAutocompleteView.as_view(),
                name='questionnaire_autocomplete'
            ),
            path(
                '<pk>/',
                include([
                    path(
                        '',
                        views.QuestionnaireDetailView.as_view(),
                        name='questionnaire_detail'
                    ),
                    path(
                        'change/',
                        views.QuestionnaireUpdateView.as_view(),
                        name='questionnaire_change'
                    ),
                    path(
                        'delete/',
                        views.QuestionnaireDeleteView.as_view(),
                        name='questionnaire_delete'
                    ),
                    path(
                        'resolve/',
                        views.QuestionnaireResolveView.as_view(),
                        name='questionnaire_resolve'
                    ),
                ])
            )
        ])
    ),
    path(
        'users/', include([
            path(
                '',
                views.UserListView.as_view(),
                name='customuser_list'
            ),
            path(
                'add/',
                views.UserCreateView.as_view(),
                name='customuser_add'
            ),
            path(
                '<pk>/',
                include([
                    path(
                        'change/',
                        views.UserUpdateView.as_view(),
                        name='customuser_change'
                    ),
                    path(
                        'delete/',
                        views.UserDeleteView.as_view(),
                        name='customuser_delete'
                    ),
                    path(
                        'password/',
                        views.UserPasswordView.as_view(),
                        name='customuser_password'
                    ),
                ])
            )
        ])
    )
]

solutions/problem-03/estela-master/estudio_covid/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'i18n/',
        include('django.conf.urls.i18n')
    ),
    path(
        'jsi18n/',
        JavaScriptCatalog.as_view(),
        name='javascript-catalog'
    ),
    path(
        '',
        include(('panel.urls', 'panel'), namespace='panel')
    )
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

solutions/problem-03/estela-master/estudio_covid/panel/forms/choice.py
from django import forms
from django.forms import inlineformset_factory

from questions.models import ChoiceEntry, Question


class ChoiceEntryForm(forms.ModelForm):
    class Meta:
        exclude = (
            'created_at', 'updated_at', 'created_by', 'updated_by'
        )
        model = ChoiceEntry
        widgets = {
            'text': forms.TextInput
        }


QuestionChoiceEntryFormSet = inlineformset_factory(
    Question,
    ChoiceEntry,
    form=ChoiceEntryForm,
    extra=1
)

solutions/problem-03/estela-master/estudio_covid/panel/forms/question.py
from django import forms

from questions.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        exclude = (
            'created_at', 'updated_at', 'created_by', 'updated_by'
        )
        model = Question
        widgets = {
            'text': forms.TextInput
        }

solutions/problem-03/estela-master/estudio_covid/panel/views/account.py
from django.contrib.auth import get_user_model, login as auth_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView,
    PasswordChangeDoneView
)
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, UpdateView

from boilerplate.mixins import UpdateMessageMixin

from panel import forms


UserModel = get_user_model()


class AccountDetailView(LoginRequiredMixin, DetailView):
    model = UserModel
    template_name = 'panel/account/account_detail.html'

    def get_object(self):
        return self.request.user


class AccountLoginView(LoginView):
    form_class = forms.AuthenticationForm
    redirect_authenticated_user = False
    success_url = reverse_lazy('panel:index')
    template_name = 'panel/account/account_login.html'

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        user = form.get_user()

        auth_login(
            self.request,
            user,
            backend='django.contrib.auth.backends.ModelBackend'
        )
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or self.success_url


class AccountLogoutView(LogoutView):
    next_page = reverse_lazy('panel:account_login')
    template_name = 'panel/account/account_logout.html'


class AccountPasswordResetView(PasswordResetView):
    email_template_name = 'panel/account/account_password_reset_email.txt'
    html_email_template_name = (
        'panel/account/account_password_reset_email.html'
    )
    subject_template_name = 'panel/account/account_password_reset_subject.txt'
    success_url = reverse_lazy('panel:account_password_reset_done')
    template_name = 'panel/account/account_password_reset_form.html'


class AccountPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'panel/account/account_password_reset_done.html'


class AccountPasswordResetConfirmView(PasswordResetConfirmView):
    post_reset_login = True
    post_reset_login_backend = 'django.contrib.auth.backends.ModelBackend'
    success_url = reverse_lazy('panel:account_password_reset_complete')
    template_name = 'panel/account/account_password_reset_confirm.html'


class AccountPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'panel/account/account_password_reset_complete.html'


class AccountPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('panel:account_password_change_done')
    template_name = 'panel/account/account_password_change_form.html'


class AccountPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'panel/account/account_password_change_done.html'


class AccountUpdateView(UpdateMessageMixin, UpdateView):
    form_class = forms.AccountChangeForm
    model = UserModel
    success_message = _("Your account has been update successfully.")
    success_url = reverse_lazy('panel:account_detail')
    template_name = 'panel/account/account_form.html'

    def get_object(self):
        return self.request.user

solutions/problem-03/estela-master/estudio_covid/panel/views/base.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, View

from sentry_sdk import last_event_id


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'panel/index.html'
    raise_exception = False


class ErrorTestView(View):
    raise_exception = True

    def get(self, request, *args, **kwargs):
        if any([request.user.is_staff, request.user.is_superuser]):
            raise NotImplementedError
        return HttpResponse('How did you get here?', content_type='text/plain')


def handler500(request, *args, **kwargs):
    return render(request, '500.html', {
        'sentry_event_id': last_event_id(),
    }, status=500)

solutions/problem-03/estela-master/estudio_covid/panel/views/question.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
)

from boilerplate.mixins import (
    ActionListMixin, CreateMessageMixin, DeleteMessageMixin,
    ExtraFormsAndFormsetsMixin, UpdateMessageMixin
)

from panel import forms
from questions.models import Question


class QuestionCreateView(
    ExtraFormsAndFormsetsMixin, PermissionRequiredMixin, CreateMessageMixin,
    CreateView
):
    form_class = forms.QuestionForm
    model = Question
    template_name = 'panel/question/question_form.html'
    permission_required = 'questions:add_question'

    def get_formset_list(self):
        return (
            forms.QuestionChoiceEntryFormSet,
        )


class QuestionDeleteView(
    PermissionRequiredMixin, DeleteMessageMixin, DeleteView
):
    model = Question
    permission_required = 'questions:delete_question'
    template_name = 'panel/question/question_form.html'
    success_url = reverse_lazy('panel:question_list')


class QuestionDetailView(PermissionRequiredMixin, DetailView):
    model = Question
    template_name = 'panel/question/question_detail.html'
    permission_required = 'questions:view_question'


class QuestionListView(ActionListMixin, PermissionRequiredMixin, ListView):
    action_list = ('add', )
    model = Question
    paginate_by = 30
    template_name = 'panel/question/question_list.html'
    permission_required = 'questions:view_question'


class QuestionUpdateView(
    ExtraFormsAndFormsetsMixin, PermissionRequiredMixin, UpdateMessageMixin,
    UpdateView
):
    form_class = forms.QuestionForm
    model = Question
    permission_required = 'questions:change_question'
    template_name = 'panel/question/question_form.html'

    def get_formset_list(self):
        return (
            forms.QuestionChoiceEntryFormSet,
        )

solutions/problem-03/estela-master/estudio_covid/panel/views/user.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DeleteView, ListView, UpdateView
)

from boilerplate.mixins import (
    ActionListMixin, CreateMessageMixin, DeleteMessageMixin, UpdateMessageMixin
)

from panel import forms


UserModel = get_user_model()


class UserListView(ActionListMixin, PermissionRequiredMixin, ListView):
    action_list = ('add', )
    model = UserModel
    paginate_by = 30
    permission_required = 'common:view_customuser'
    template_name = 'panel/user/user_list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_superuser:
            qs = qs.filter(
                is_superuser=False
            )
        if not self.request.user.is_staff:
            qs = qs.filter(
                is_staff=False
            )
        return qs


class UserCreateView(
    PermissionRequiredMixin, CreateMessageMixin, CreateView
):
    form_class = forms.UserCreateForm
    model = UserModel
    permission_required = 'common:add_customuser'
    success_url = reverse_lazy("panel:user_list")
    template_name = 'panel/user/user_form.html'


class UserDeleteView(
    PermissionRequiredMixin, DeleteMessageMixin, DeleteView
):
    model = UserModel
    permission_required = 'common:delete_customuser'
    success_url = reverse_lazy("panel:user_list")
    template_name = 'panel/user/user_form.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_superuser:
            qs = qs.filter(
                is_superuser=False
            )
        if not self.request.user.is_staff:
            qs = qs.filter(
                is_staff=False
            )
        return qs


class UserUpdateView(
    PermissionRequiredMixin, UpdateMessageMixin, UpdateView
):
    form_class = forms.UserUpdateForm
    model = UserModel
    permission_required = 'common:change_customuser'
    success_url = reverse_lazy("panel:user_list")
    template_name = 'panel/user/user_form.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_superuser:
            qs = qs.filter(
                is_superuser=False
            )
        if not self.request.user.is_staff:
            qs = qs.filter(
                is_staff=False
            )
        return qs


class UserPasswordView(
    PermissionRequiredMixin, UpdateMessageMixin, UpdateView
):
    form_class = SetPasswordForm
    model = UserModel
    permission_required = 'common:change_customuser'
    success_url = reverse_lazy('panel:user_list')
    template_name = 'panel/user/user_form.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_superuser:
            qs = qs.filter(
                is_superuser=False
            )
        if not self.request.user.is_staff:
            qs = qs.filter(
                is_staff=False
            )
        return qs

    def get_form(self):
        kwargs = self.get_form_kwargs()
        kwargs.pop('instance')

        return self.get_form_class()(
            user=self.get_object(), **kwargs
        )

solutions/problem-03/estela-master/estudio_covid/panel/templates/panel/blocks/_footer-text.html
{% load i18n %}

{% trans "Build with" %}
<span class="text-danger glyphicon glyphicon-heart" aria-hidden="true"></span>
{% trans "from Perú" %}

solutions/problem-03/estela-master/estudio_covid/panel/templates/panel/blocks/_footer.html
{% load i18n %}


{% if not view.is_popup %}
  <div class="footer">
    <div class="row">
      <div class="col ml-auto">
        <strong>{% trans "Copyright" %}</strong> &copy; {% now 'Y' %}.
        {% include 'panel/blocks/_footer-text.html' %}
      </div>
    </div>
  </div>
{% endif %}

solutions/problem-03/estela-master/estudio_covid/panel/templates/panel/blocks/_sidebar.html
{% load i18n %}

<nav class="navbar-default navbar-static-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div id="remoteDropdownProfile" class="dropdown profile-element">
          {% if request.user.photo_thumb %}
          <span><img src="{{ request.user.photo_thumb.url }}" class="img-circle" alt="{{ request.user }}" height="48px"
              width="48px"></span>
          {% endif %}
          <a data-toggle="dropdown" href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">
            <span class="clear">
              <span class="block m-t-xs"><strong class="font-bold">{{ request.user }}</strong></span>
              <span class="text-muted text-xs block">Estudio COVID <b class="caret"></b></span>
            </span>
          </a>
          <ul class="dropdown-menu animated fadeIn m-t-xs" aria-labelledby="profileBtn">
            {% if request.user.is_staff %}
            <li><a href="{% url 'admin:index' %}">{% trans 'admin' %}</a></li>
            <li id="companies" class="divider"></li>
            {% endif %}
            <li class="divider" ng-if="data.colaborator_set.length > 0"></li>
            <li><a href="{% url 'panel:account_detail' %}">{% trans 'profile' %}</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'panel:account_logout' %}">{% trans 'logout' %}</a></li>
          </ul>
        </div>
        <div class="logo-element">EC+</div>
      </li>
      {% with request.resolver_match as resolver_match %}
      <li class="{% if resolver_match.url_name == 'index' %} active{% endif %}">
        <a href="{% url 'panel:index' %}">
          <i class="fas fa-home"></i>
          <span class="nav-label">{% trans "dashboard" %}</span>
        </a>
      </li>
      <li {% if 'question_' in resolver_match.url_name %}class="active" {% endif %}>
        <a href="{% url 'panel:question_list' %}">
          <i class="fas fa-question"></i>
          <span class="nav-label">{% trans "questions" %}</span>
        </a>
      </li>
      <li {% if 'questionnaire_' in resolver_match.url_name %}class="active" {% endif %}>
        <a href="{% url 'panel:questionnaire_list' %}">
          <i class="fas fa-print"></i>
          <span class="nav-label">{% trans "questionnaires" %}</span>
        </a>
      </li>
      <li {% if 'customuser_' in resolver_match.url_name %}class="active" {% endif %}>
        <a href="{% url 'panel:customuser_list' %}">
          <i class="fas fa-user"></i>
          <span class="nav-label">{% trans "users" %}</span>
        </a>
      </li>
      {% endwith %}
    </ul>
  </div>
</nav>

solutions/problem-03/estela-master/estudio_covid/panel/templates/panel/blocks/_top-navigation.html
{% load i18n %}

<div class="row border-bottom">
  <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i></a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
      <li class="dropdown visible-xs-inline-block">
        <a class="dropdown-toggle" href="{% url 'panel:account_detail' %}" data-toggle="dropdown"><i
            class="fa fa-user"></i></a>
        <ul class="dropdown-menu">
          {% if request.user.is_staff %}
          <li><a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
          <li class="divider"></li>
          {% endif %}
          <li><a href="{% url 'panel:account_detail' %}">{% trans 'Profile' %}</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'panel:account_logout' %}"><i class="fa fa-sign-out"></i> {% trans "logout" %}</a>
      </li>
    </ul>
  </nav>
</div>